DROP TABLE SCHEDULE_STUDENTS;
DROP TABLE SCHEDULE;
DROP TABLE COURSES;
DROP TABLE STUDENTS;
DROP TABLE USERS;

DROP SEQUENCE SCHEDULE_STUDENTS_SEQ;
DROP SEQUENCE SCHEDULE_SEQ;
DROP SEQUENCE USER_SEQ;
DROP SEQUENCE STUDENTS_SEQ;
DROP SEQUENCE COURSES_SEQ;
DROP SEQUENCE STUDENTS_COURSES_SEQ;