ALTER SESSION SET CONTAINER=ORCLPDB;


CREATE USER studentms IDENTIFIED BY studentms;
GRANT ALL PRIVILEGES TO studentms;

CREATE TABLE USERS (
    ID NUMBER(6) PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(512) NOT NULL
);

CREATE TABLE STUDENTS (
    ID NUMBER(6) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    SECOND_NAME VARCHAR2(50) NOT NULL,
    THIRD_NAME VARCHAR2(50) NOT NULL,
    FOURTH_NAME VARCHAR2(50) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
	GENDER VARCHAR2(1) NOT NULL,
    USER_ID NUMBER(6),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE COURSES (
    ID NUMBER(6) PRIMARY KEY,
    CODE VARCHAR2(10) UNIQUE NOT NULL,
    NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE SCHEDULE (
	ID NUMBER(12) PRIMARY KEY,
	COURSE_ID NUMBER(6) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID)
);

CREATE TABLE SCHEDULE_STUDENTS (
    ID NUMBER(9) PRIMARY KEY,
	SCHEDULE_ID NUMBER(12) NOT NULL,
    STUDENT_ID NUMBER(6) NOT NULL,
	REGISTRATION_DATE DATE DEFAULT SYSDATE NOT NULL,
	FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID),
    CONSTRAINT UNIQUE_SCHEDULE_STUDENT UNIQUE (SCHEDULE_ID, STUDENT_ID)
);


CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE STUDENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COURSES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SCHEDULE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SCHEDULE_STUDENTS_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES (USER_SEQ.NEXTVAL,'admin','$2a$10$OwONg.R4QE5TqoZQtDKqz.UlEKYrnxBesF8bRcRBCmZsOjidM8aSu');
INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES (USER_SEQ.NEXTVAL,'student1','$2a$10$/afXS/A74nPRbCdtdHVuDeyF5Ek0suiR9Q8as5mbS.6OfumP5W9WC');
INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES (USER_SEQ.NEXTVAL,'student2','$2a$10$/afXS/A74nPRbCdtdHVuDeyF5Ek0suiR9Q8as5mbS.6OfumP5W9WC');
INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES (USER_SEQ.NEXTVAL,'student3','$2a$10$/afXS/A74nPRbCdtdHVuDeyF5Ek0suiR9Q8as5mbS.6OfumP5W9WC');
INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES (USER_SEQ.NEXTVAL,'student4','$2a$10$/afXS/A74nPRbCdtdHVuDeyF5Ek0suiR9Q8as5mbS.6OfumP5W9WC');
INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES (USER_SEQ.NEXTVAL,'student5','$2a$10$/afXS/A74nPRbCdtdHVuDeyF5Ek0suiR9Q8as5mbS.6OfumP5W9WC');
INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES (USER_SEQ.NEXTVAL,'student6','$2a$10$/afXS/A74nPRbCdtdHVuDeyF5Ek0suiR9Q8as5mbS.6OfumP5W9WC');
INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES (USER_SEQ.NEXTVAL,'student7','$2a$10$/afXS/A74nPRbCdtdHVuDeyF5Ek0suiR9Q8as5mbS.6OfumP5W9WC');
INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES (USER_SEQ.NEXTVAL,'student8','$2a$10$/afXS/A74nPRbCdtdHVuDeyF5Ek0suiR9Q8as5mbS.6OfumP5W9WC');


INSERT INTO STUDENTS(ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,FOURTH_NAME,BIRTH_DATE,GENDER,USER_ID) VALUES(STUDENTS_SEQ.NEXTVAL,'Mohammad','Gamal','Aly','Mohammad', TO_DATE('2000-01-01', 'YYYY-MM-DD'),'M', 2);
INSERT INTO STUDENTS(ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,FOURTH_NAME,BIRTH_DATE,GENDER,USER_ID) VALUES(STUDENTS_SEQ.NEXTVAL,'Fareed','Ahmad','Mahmoud','Zeyad', TO_DATE('1999-09-26', 'YYYY-MM-DD'),'M', 3);
INSERT INTO STUDENTS(ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,FOURTH_NAME,BIRTH_DATE,GENDER,USER_ID) VALUES(STUDENTS_SEQ.NEXTVAL,'Zeinab','Ismail','Mohammad','Yaser', TO_DATE('2001-05-09', 'YYYY-MM-DD'),'F', 4);
INSERT INTO STUDENTS(ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,FOURTH_NAME,BIRTH_DATE,GENDER,USER_ID) VALUES(STUDENTS_SEQ.NEXTVAL,'Esmat','Foad','Omar','Sameh', TO_DATE('1996-11-18', 'YYYY-MM-DD'),'M', 5);
INSERT INTO STUDENTS(ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,FOURTH_NAME,BIRTH_DATE,GENDER,USER_ID) VALUES(STUDENTS_SEQ.NEXTVAL,'Morad','Ahmad','Mohammad','Ahmad', TO_DATE('2006-10-08', 'YYYY-MM-DD'),'M', 6);
INSERT INTO STUDENTS(ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,FOURTH_NAME,BIRTH_DATE,GENDER,USER_ID) VALUES(STUDENTS_SEQ.NEXTVAL,'Dina','Ahmad','Mohammad','Ahmad', TO_DATE('2006-10-08', 'YYYY-MM-DD'),'F', 7);
INSERT INTO STUDENTS(ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,FOURTH_NAME,BIRTH_DATE,GENDER,USER_ID) VALUES(STUDENTS_SEQ.NEXTVAL,'Donya','Ahmad','Mohammad','Ahmad', TO_DATE('2003-03-31', 'YYYY-MM-DD'),'F', 8);
INSERT INTO STUDENTS(ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,FOURTH_NAME,BIRTH_DATE,GENDER,USER_ID) VALUES(STUDENTS_SEQ.NEXTVAL,'Yehia','Hamed','Adel','Tamer', TO_DATE('2003-03-31', 'YYYY-MM-DD'),'M', 9);

INSERT INTO COURSES(ID,CODE,NAME) VALUES(COURSES_SEQ.NEXTVAL,'JA101','Java Object Oriented Programming');
INSERT INTO COURSES(ID,CODE,NAME) VALUES(COURSES_SEQ.NEXTVAL,'JA102','Java Data Structures');
INSERT INTO COURSES(ID,CODE,NAME) VALUES(COURSES_SEQ.NEXTVAL,'ALG00','Computing Algorithms');
INSERT INTO COURSES(ID,CODE,NAME) VALUES(COURSES_SEQ.NEXTVAL,'ORCL00','Introduction To Oracle Database');
INSERT INTO COURSES(ID,CODE,NAME) VALUES(COURSES_SEQ.NEXTVAL,'ORCL11','Oracle SQL');
INSERT INTO COURSES(ID,CODE,NAME) VALUES(COURSES_SEQ.NEXTVAL,'ORCL12','Oracle PL/SQL');
INSERT INTO COURSES(ID,CODE,NAME) VALUES(COURSES_SEQ.NEXTVAL,'ORCL61','Oracle DBA 1');
INSERT INTO COURSES(ID,CODE,NAME) VALUES(COURSES_SEQ.NEXTVAL,'ORCL62','Oracle DBA 2');

INSERT INTO SCHEDULE(ID,COURSE_ID,START_DATE,END_DATE) VALUES(SCHEDULE_SEQ.NEXTVAL,1,TO_DATE('2024-01-01', 'YYYY-MM-DD'),TO_DATE('2024-03-31', 'YYYY-MM-DD'));
INSERT INTO SCHEDULE(ID,COURSE_ID,START_DATE,END_DATE) VALUES(SCHEDULE_SEQ.NEXTVAL,1,TO_DATE('2024-05-01', 'YYYY-MM-DD'),TO_DATE('2024-08-31', 'YYYY-MM-DD'));
INSERT INTO SCHEDULE(ID,COURSE_ID,START_DATE,END_DATE) VALUES(SCHEDULE_SEQ.NEXTVAL,1,TO_DATE('2024-11-01', 'YYYY-MM-DD'),TO_DATE('2025-01-15', 'YYYY-MM-DD'));
INSERT INTO SCHEDULE(ID,COURSE_ID,START_DATE,END_DATE) VALUES(SCHEDULE_SEQ.NEXTVAL,2,TO_DATE('2024-10-24', 'YYYY-MM-DD'),TO_DATE('2024-12-28', 'YYYY-MM-DD'));

INSERT INTO SCHEDULE_STUDENTS(ID,SCHEDULE_ID,STUDENT_ID,REGISTRATION_DATE) VALUES (SCHEDULE_STUDENTS_SEQ.NEXTVAL,1,1,TO_DATE('2023-11-18 11:12:52', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_STUDENTS(ID,SCHEDULE_ID,STUDENT_ID,REGISTRATION_DATE) VALUES (SCHEDULE_STUDENTS_SEQ.NEXTVAL,1,3,TO_DATE('2023-11-21 08:10:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_STUDENTS(ID,SCHEDULE_ID,STUDENT_ID,REGISTRATION_DATE) VALUES (SCHEDULE_STUDENTS_SEQ.NEXTVAL,1,4,TO_DATE('2023-11-22 19:25:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_STUDENTS(ID,SCHEDULE_ID,STUDENT_ID,REGISTRATION_DATE) VALUES (SCHEDULE_STUDENTS_SEQ.NEXTVAL,1,5,TO_DATE('2024-03-05 10:00:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_STUDENTS(ID,SCHEDULE_ID,STUDENT_ID,REGISTRATION_DATE) VALUES (SCHEDULE_STUDENTS_SEQ.NEXTVAL,2,2,TO_DATE('2024-04-15 10:58:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_STUDENTS(ID,SCHEDULE_ID,STUDENT_ID,REGISTRATION_DATE) VALUES (SCHEDULE_STUDENTS_SEQ.NEXTVAL,2,6,TO_DATE('2024-04-16 09:49:49', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO SCHEDULE_STUDENTS(ID,SCHEDULE_ID,STUDENT_ID,REGISTRATION_DATE) VALUES (SCHEDULE_STUDENTS_SEQ.NEXTVAL,3,1,TO_DATE('2024-08-23 15:26:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_STUDENTS(ID,SCHEDULE_ID,STUDENT_ID,REGISTRATION_DATE) VALUES (SCHEDULE_STUDENTS_SEQ.NEXTVAL,3,2,TO_DATE('2023-09-15 13:07:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO SCHEDULE_STUDENTS(ID,SCHEDULE_ID,STUDENT_ID,REGISTRATION_DATE) VALUES (SCHEDULE_STUDENTS_SEQ.NEXTVAL,3,3,TO_DATE('2023-09-15 15:21:56', 'YYYY-MM-DD HH24:MI:SS'));

COMMIT;